# Generated by Django 3.1.7 on 2021-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='supplier',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
