# Generated by Django 3.1.7 on 2021-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0002_extra_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='extra_type',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Drink'), (2, 'Equipment')], default=0),
        ),
    ]
