# Generated by Django 3.1.7 on 2021-03-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0004_auto_20210331_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='breakdownTime',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extras',
            field=models.ManyToManyField(null=True, through='roombooking.ExtraBookingMap', to='roombooking.Extra'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='booking length'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='setupTime',
            field=models.TimeField(default=0),
        ),
    ]
