# Generated by Django 3.1.7 on 2021-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0006_auto_20210331_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='extra_type',
            field=models.IntegerField(choices=[(0, 'Catering'), (1, 'Refreshments'), (2, 'Equipment')], default=0),
        ),
    ]
