# Generated by Django 3.1.7 on 2021-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0007_auto_20210405_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrabookingmap',
            name='timing',
            field=models.TimeField(default='0:00'),
        ),
    ]
