# Generated by Django 3.1.7 on 2021-04-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roombooking', '0008_extrabookingmap_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal_booking',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
