# Generated by Django 3.1.7 on 2021-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0011_auto_20210414_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.IntegerField(choices=[(0, '8:00'), (1, '8:30'), (2, '9:00'), (3, '9:30'), (4, '10:00'), (5, '10:30'), (6, '11:00'), (7, '11:30'), (8, '12:00'), (9, '12:30'), (10, '13:00'), (11, '13:30'), (12, '14:00'), (13, '14:30'), (14, '15:00'), (15, '15:30'), (16, '16:00'), (17, '16:30'), (18, '17:00'), (19, '17:30'), (10, '18:00')], default=0),
        ),
    ]
