# Generated by Django 3.1.7 on 2021-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0014_auto_20210418_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='length',
            field=models.IntegerField(choices=[(1, '0:30'), (2, '1:00'), (3, '1:30'), (4, '2:00'), (5, '2:30'), (6, '3:00'), (7, '3:30'), (8, '4:00'), (9, '4:30'), (10, '5:00'), (11, '5:30'), (12, '6:00'), (13, '6:30'), (14, '7:00'), (15, '7:30'), (16, '8:00'), (17, '8:30'), (18, '9:00'), (19, '9:30'), (20, '10:00')], default=0),
        ),
    ]
