# Generated by Django 3.1.7 on 2021-04-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0015_auto_20210419_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('extraPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roombooking.booking')),
            ],
        ),
    ]
