# Generated by Django 3.1.7 on 2021-04-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0016_auto_20210419_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='Cost',
        ),
    ]
