# Generated by Django 3.1.7 on 2021-04-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0017_auto_20210419_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roombooking.booking'),
        ),
    ]
