# Generated by Django 3.1.7 on 2021-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0019_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='breakdownTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='setupTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
