# Generated by Django 3.1.7 on 2021-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0021_auto_20210430_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='note',
        ),
        migrations.AddField(
            model_name='extrabookingmap',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
