# Generated by Django 3.1.7 on 2021-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0022_auto_20210430_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendees',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
